##
## Makefile for lem_in in /home/fourri_l/Projects/repo-lemin
## 
## Made by Laurent Fourrier
## Login   <fourri_l@epitech.net>
## 
## Started on  Sun May 04 13:59:17 2014 Laurent Fourrier
## Last update Sun May  4 13:59:23 2014 Laurent Fourrier
##

## Makefile automatically generated by TPrCfg

CC	=	cc

RM	=	rm -rf

SRCDIR	=	src

LIBDIR	=	lib

INCDIR	=	include

CFLAGS	=	-Wall \
		-iquote$(INCDIR)	\
		-I$(LIBDIR)/tlist/include	\
		-I$(LIBDIR)/tsys/include	\

LDFLAGS	= \
		-ltlist -L$(LIBDIR)/tlist/	\
		-ltsys -L$(LIBDIR)/tsys/	\

SRC	=	$(SRCDIR)/check_side.c	\
		$(SRCDIR)/get_room.c	\
		$(SRCDIR)/work_on_list.c	\
		$(SRCDIR)/init_struct.c	\
		$(SRCDIR)/check_cmd.c	\
		$(SRCDIR)/solve_lemin.c	\
		$(SRCDIR)/link_utl.c	\
		$(SRCDIR)/strcat_lemin.c	\
		$(SRCDIR)/add_link.c	\
		$(SRCDIR)/read_entry.c	\
		$(SRCDIR)/main.c	\
		$(SRCDIR)/add_new_list.c	\
		$(SRCDIR)/solve/get_path_list.c	\
		$(SRCDIR)/solve/compute_paths.c	\
		$(SRCDIR)/solve/tl_path_len.c	\
		$(SRCDIR)/solve/tl_get_last_node.c	\
		$(SRCDIR)/solve/print_solution.c	\
		$(SRCDIR)/solve/update_paths.c	\
		$(SRCDIR)/solve/add_old_nodes.c	\
		$(SRCDIR)/solve/tl_room_exists.c	\

OBJ	=	$(SRC:.c=.o)

NAME	=	lem_in

all: libs $(NAME)

$(NAME): $(OBJ)
	$(CC) -o $(NAME) $(OBJ) $(LDFLAGS)

libs:
	cd $(LIBDIR)/tlist && make
	cd $(LIBDIR)/tsys && make

clean:
	$(RM) $(OBJ)
	cd $(LIBDIR)/tlist && make clean
	cd $(LIBDIR)/tsys && make clean

fclean: clean
	$(RM) $(NAME)
	cd $(LIBDIR)/tlist && make fclean
	cd $(LIBDIR)/tsys && make fclean

re: fclean all
